trigger:
    - preprod

pool:
    vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - job: Build
            pool:
                vmImage: 'ubuntu-latest'
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: '19.x'
                  displayName: 'Install Node.js 19.x'

                - script: |
                      cd AngularWithAzure/
                      npm install -g @angular/cli
                      npm install
                      npm run build-preprod
                  displayName: 'npm install and build'
                  workingDirectory: '$(Build.SourcesDirectory)'

                - task: CopyFiles@2
                  inputs:
                      sourceFolder: '$(Build.SourcesDirectory)/dist/mi-movilidad/'
                      Contents: '**'
                      TargetFolder: '$(build.ArtifactStagingDirectory)'

                - task: ArchiveFiles@2
                  inputs:
                      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
                      includeRootFolder: true
                      archiveType: zip
                      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                      replaceExistingArchive: true

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                      ArtifactName: 'drop'